name: 'Check for Latest Ollama Tag'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ollama-version-tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Get Repo Tag
      id: repo-tag
      run: |
        git fetch --tags
        echo "CURRENT_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        echo "📝 Fetched repository tag."

    - name: Fetch Ollama Tag
      id: ollama-tag
      uses: brainxio/fetch-latest-github-tag@v1
      with:
        owner: ollama
        repo: ollama
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Compare Versions
      uses: brainxio/compare-versions@v1
      with:
        source-version: ${{ env.CURRENT_VERSION }}
        target-version: ${{ env.GH_OLLAMA_OLLAMA_LATEST_TAG }}

    - name: Telegram Notification - Latest Tag
      if: success() && env.GH_OLLAMA_OLLAMA_LATEST_TAG != env.CURRENT_VERSION
      uses: brainxio/telegram-bot-action@v1
      with:
        bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: "🔍 Fetched latest Ollama tag: ${{ env.GH_OLLAMA_OLLAMA_LATEST_TAG }}"

    - name: Create New Tag and Push Changes
      if: success() && env.GH_OLLAMA_OLLAMA_LATEST_TAG != env.CURRENT_VERSION
      run: |
        # Determine the new version
        NEW_VERSION=${{ env.HIGHEST_VERSION }}

        # Commit the changes
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        # Tag and push the changes
        git tag ${GH_OLLAMA_OLLAMA_LATEST_TAG} -m "(Auto) Release ${GH_OLLAMA_OLLAMA_LATEST_TAG}"
        git push origin main ${GH_OLLAMA_OLLAMA_LATEST_TAG}
        echo "🤖 Created new tag ${GH_OLLAMA_OLLAMA_LATEST_TAG}."
        echo "🚀 Pushed changes to repository."

    - name: Telegram Notification - New Tag Created
      if: success() && env.GH_OLLAMA_OLLAMA_LATEST_TAG != env.CURRENT_VERSION
      uses: brainxio/telegram-bot-action@v1
      with:
        bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: "🏷️ Created and pushed new tag: ${{ env.GH_OLLAMA_OLLAMA_LATEST_TAG }}"

    - name: Telegram Notification - Error
      if: ${{ failure() }}
      uses: brainxio/telegram-bot-action@v1
      with:
        bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: "❌ Failed to fetch latest Ollama tag. Please check the workflow."
